base_url = "https://sekky89.github.io"
title = "sekky89"
description = "しがないエンジニアのメモ置場"
author = "sekky89"
compile_sass = true

default_language = "en"
generate_feeds = true
feed_filenames = ["atom.xml"]
taxonomies = [{ name = "tags", rss = true, paginate_by = 5 }]

build_search_index = true
theme = "kita"

[markdown]
# extra_syntaxes_and_themes = []

[markdown.highlighting]
dark_theme = "base16-ocean-dark"

[extra]
math = true
mermaid = true
comment = false
side_toc = true
social_image = "icons/github.svg"

[extra.style]

[extra.profile]
name = "sekky89"
bio = "物置"
avatar_url = "icons/github.svg"
avater_invert = true

[[extra.profile.social]]
name = "github"
url = "https://github.com/sekky89"

# [[extra.profile.social]]
# name = "x"
# url = ""

[[extra.profile.social]]
name = "rss"
url = "$BASE_URL/atom.xml"

[[extra.menu]]
name = "Projects"
url = "$BASE_URL/projects"

[[extra.menu]]
name = "Archive"
url = "$BASE_URL/archive"

[[extra.menu]]
name = "Tags"
url = "$BASE_URL/tags"

[[extra.menu]]
name = "About"
url = "$BASE_URL/about"

# [extra.footer]
# since = 2020
# license = "CC BY-SA 4.0"
# license_url = "https://creativecommons.org/licenses/by-sa/4.0/deed"
